job/urls.py
from django.urls import path
from . import views
from .import api

app_name="job"
urlpatterns = [
    path("job_list",views.job_list,name="job_list"),
    path("add_job",views.add_jobs,name="add_job"),
    path("<str:slug>",views.job_detail,name="job_detail"),
    
    #API
    path("api/list",api.API,name="api"),
    path("api/list/<str:id>",api.API_detail,name="api"),
       
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/',include("django.contrib.auth.urls")),
    path('accounts/',include("accounts.urls",namespace="accounts")),
    path('admin/', admin.site.urls),
    path('home/',include("home.urls")),
    path('blog/',include("blog.urls")),
    path('accounts/',include("accounts.urls")),
    path('jobs/',include("job.urls",namespace="jobs")),
    path('contact-us/',include("contact.urls",namespace='contact-us')),
    path('api-auth/', include('rest_framework.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
# Create your models here.

# django model field
JOB_TYPE = [
    ("Full Time", "Full Time"),
    ("Part Time", "Part Time"),
]

class job (models.Model):  # table
    owner=models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    job_type = models.CharField(max_length=15, choices=JOB_TYPE)
    description = models.CharField(max_length=1000)
    published_at = models.DateTimeField(auto_now=True)
    vacancy = models.IntegerField(default=1)
    salary = models.IntegerField(default=0)
    image=models.ImageField(upload_to="jobs/")
    experienc = models.IntegerField(default=1)
    cateogry = models.ForeignKey('Cateogry', on_delete=models.CASCADE)
    slug=models.SlugField(blank=True ,null=True)
    
    def save(self,*args,**kwargs):
        self.slug=slugify(self.title)
        super(job,self).save(*args,**kwargs)

    def __str__(self):
        return self.title


class Cateogry (models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name


class Applay (models.Model):
    job=models.ForeignKey(job,on_delete=models.CASCADE)
    name=models.CharField(max_length=15)
    email=models.EmailField(max_length=50)
    website=models.URLField()
    cv=models.FileField(upload_to="cv/")
    texteria=models.TextField(max_length=100)
    created_at=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name

job/views.py
from django.urls import reverse
from django.shortcuts import redirect, render
from .models import job
from django.core.paginator import Paginator
from .form import Applay_form, add_job
from django.contrib.auth.decorators import login_required
from .filters import job_filter
# Create your views here.


def job_list(requset):
    job_list = job.objects.all()
    my_filter=job_filter(requset.GET,queryset=job_list)
    job_list=my_filter.qs
    paginator = Paginator(job_list, 20)
    page_number = requset.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {"job_list": page_obj,"my_filter":my_filter}
    return render(requset, 'job/job_list.html', context)

@login_required
def job_detail(requset, slug):
    job_detail = job.objects.get(slug=slug)
    
    if requset.method == "POST":
        form = Applay_form(requset.POST, requset.FILES)
        if form.is_valid():
            my_form = form.save(commit=False)
            my_form.job = job_detail
        form.save()
        return redirect(reverse("jobs:job_list"))
    
    else:
        form = Applay_form()
    context = {'job_detail': job_detail, 'form': form}
    return render(requset, 'job/job_detail.html', context)

@login_required
def add_jobs(requset):
    if requset.method == "POST":
        add = add_job(requset.POST, requset.FILES)
        if add.is_valid():
            myadd = add.save(commit=False)
            myadd.owner = requset.user
        add.save()
        return redirect(reverse("jobs:job_list"))

    else:
        add = add_job()
    context = {"add_job": job.objects.all(), "add": add}
    return render(requset, 'job/add_job.html', context)

job/templates/job/add_job.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="bradcam_text">
          <h3>{{job_detail}}</h3>
        </div>
      </div>
    </div>
  </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 m-auto">
        <div class="apply_job_form white-bg">
          <h4>Apply for the job</h4>
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form add %}
            {% buttons %}
            <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
            {% endbuttons %}

   
          </form>
        </div>
      </div>
  
    </div>
  </div>
</div>
{% endblock body %}

job/templates/job/job_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="bradcam_text">
          <h3>{{job_detail}}</h3>
        </div>
      </div>
    </div>
  </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="job_details_header">
          <div class="single_jobs white-bg d-flex justify-content-between">
            <div class="jobs_left d-flex align-items-center">
              <div class="thumb">
                <img style="width: 50px;" src="{{job_detail.image.url}}" alt="">
              </div>
              <div class="jobs_conetent">
                <a href="#">
                  <h4>{{job_detail}}</h4>
                </a>
                <div class="links_locat d-flex align-items-center">
                  <div class="location">
                    <p> <i class="fa fa-map-marker"></i> California, USA</p>
                  </div>
                  <div class="location">
                    <p> <i class="fa fa-clock-o"></i> {{job_detail.job_type}}</p>
                  </div>
                </div>
              </div>
            </div>
            <div class="jobs_right">
              <div class="apply_now">
                <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
              </div>
            </div>
          </div>
        </div>
        <div class="descript_wrap white-bg">
          <div class="single_wrap">
            <h4>Job description</h4>
            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered
              alteration in some form, by injected humour, or randomised words which don't look even slightly
              believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything
              embarrassing.</p>
            <p>Variations of passages of lorem Ipsum available, but the majority have suffered alteration in some
              form, by injected humour, or randomised words which don't look even slightly believable. If you are
              going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing.</p>
          </div>
          <div class="single_wrap">
            <h4>Responsibility</h4>
            <ul>
              <li>The applicants should have experience in the following areas.
              </li>
              <li>Have sound knowledge of commercial activities.</li>
              <li>Leadership, analytical, and problem-solving abilities.</li>
              <li>Should have vast knowledge in IAS/ IFRS, Company Act, Income Tax, VAT.</li>
            </ul>
          </div>
          <div class="single_wrap">
            <h4>Qualifications</h4>
            <ul>
              <li>The applicants should have experience in the following areas.
              </li>
              <li>Have sound knowledge of commercial activities.</li>
              <li>Leadership, analytical, and problem-solving abilities.</li>
              <li>Should have vast knowledge in IAS/ IFRS, Company Act, Income Tax, VAT.</li>
            </ul>
          </div>
          <div class="single_wrap">
            <h4>Benefits</h4>
            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered
              alteration in some form, by injected humour, or randomised words which don't look even slightly
              believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything
              embarrassing.</p>
          </div>
        </div>
        <div class="apply_job_form white-bg">
          <h4>Apply for the job</h4>
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
            {% endbuttons %}

          
          </form>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="job_sumary">
          <div class="summery_header">
            <h3>Job Summery</h3>
          </div>
          <div class="job_content">
            <ul>
              <li>Published on: <span>12 Nov, 2019</span></li>
              <li>Vacancy: <span>2 Position</span></li>
              <li>Salary: <span>50k - 120k/y</span></li>
              <li>Location: <span>California, USA</span></li>
              <li>Job Nature: <span> Full-time</span></li>
            </ul>
          </div>
        </div>
        <div class="share_wrap d-flex">
          <span>Share at:</span>
          <ul>
            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
          </ul>
        </div>
        <div class="job_location_wrap">
          <div class="job_lok_inner">
            <div id="map" style="height: 200px;"></div>
            <script>
              function initMap() {
                var uluru = { lat: -25.363, lng: 131.044 };
                var grayStyles = [
                  {
                    featureType: "all",
                    stylers: [
                      { saturation: -90 },
                      { lightness: 50 }
                    ]
                  },
                  { elementType: 'labels.text.fill', stylers: [{ color: '#ccdee9' }] }
                ];
                var map = new google.maps.Map(document.getElementById('map'), {
                  center: { lat: -31.197, lng: 150.744 },
                  zoom: 9,
                  styles: grayStyles,
                  scrollwheel: false
                });
              }

            </script>
            <script
              src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock body %}

job/templates/job/job_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="bradcam_text">
          <h3>{{job_list|length}} Jobs Available</h3>
        </div>
      </div>
    </div>
  </div>
</div>
<!--/ bradcam_area  -->

<!-- job_listing_area_start  -->
<div class="job_listing_area plus_padding">
  <div class="container">
    <div class="row">
      <div class="col-lg-3">

        <div class="job_filter white-bg">
          <div class="form_inner white-bg">
            <h3>Filter</h3>
            <form action="#">
              {% bootstrap_form my_filter.form %}

              <button class="boxed-btn3 w-100 mt-4" type="submit">serch</button>

            </form>
          </div>
          <div class="range_wrap">
            <label for="amount">Price range:</label>
            <div id="slider-range"></div>
            <p>
              <input type="text" id="amount" readonly
                style="border:0; color:#7A838B; font-size: 14px; font-weight:400;">
            </p>
          </div>
          <div class="reset_btn">
          </div>
        </div>

      </div>
      <div class="col-lg-9">
        <div class="recent_joblist_wrap">
          <div class="recent_joblist white-bg ">
            <div class="row align-items-center">
              <div class="col-md-6">
                <h4>Job Listing</h4>
              </div>
              <div class="col-md-6">
                <div class="serch_cat d-flex justify-content-end">
                  <select>
                    <option data-display="Most Recent">Most Recent</option>
                    <option value="1">Marketer</option>
                    <option value="2">Wordpress </option>
                    <option value="4">Designer</option>
                  </select>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="job_lists m-0">
          <div class="row">
            {% for job in job_list %}
            <div class="col-lg-12 col-md-12">
              <div class="single_jobs white-bg d-flex justify-content-between">
                <div class="jobs_left d-flex align-items-center">
                  <div class="thumb">
                    <img style="width: 50px;" src="{{job.image.url}}" alt="">
                  </div>
                  <div class="jobs_conetent">
                    <a href="{% url 'jobs:job_detail' job.slug %}">
                      <h4>{{job}}</h4>
                    </a>
                    <div class="links_locat d-flex align-items-center">
                      <div class="location">
                        <p> <i class="fa fa-map-marker"></i> California, USA</p>
                      </div>
                      <div class="location">
                        <p> <i class="fa fa-clock-o"></i> {{job.job_type}}</p>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="jobs_right">
                  <div class="apply_now">
                    <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                    <a href="{% url 'jobs:job_detail' job.slug %}" class="boxed-btn3">Apply Now</a>
                  </div>
                  <div class="date">
                    <p>{{job.published_at}}</p>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>

          {% if job_list.has_other_pages %}

          <div class="row">
            <div class="col-lg-12">
              <div class="pagination_wrap">
                <ul>
                  {% if job_list.has_previous %}
                  <li><a href="?page={{job_list.previous_page_number}}"> 
                    <i class="ti-angle-left"></i> </a></li>
                  {% endif %}

                  {% for paginator in job_list.paginator.page_range %}
                  <li><a href="?page={{paginator}}"><span>{{paginator}}</span></a></li>
                  {% endfor %}

                  {% if job_list.has_next %}
                  <li><a href="?page={{job_list.next_page_number}}"> 
                    <i class="ti-angle-right"></i> </a></li>
                  {% endif %}

                </ul>
              </div>
            </div>
          </div>

          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
<!-- job_listing_area_end  -->

{% endblock body %}