accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns = [
    path("signup",views.signup,name="signup"),
    path("profile",views.profile,name="profile"),
    path("profile/edit",views.profile_edit,name="profile_edit")
] 

job/urls.py
from django.urls import path
from . import views
from .import api

app_name="job"
urlpatterns = [
    path("job_list",views.job_list,name="job_list"),
    path("add_job",views.add_jobs,name="add_job"),
    path("<str:slug>",views.job_detail,name="job_detail"),
    
    #API
    path("api/list",api.API,name="api"),
    path("api/list/<str:id>",api.API_detail,name="api"),
       
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/',include("django.contrib.auth.urls")),
    path('accounts/',include("accounts.urls",namespace="accounts")),
    path('admin/', admin.site.urls),
    path('home/',include("home.urls")),
    path('blog/',include("blog.urls")),
    path('accounts/',include("accounts.urls")),
    path('jobs/',include("job.urls",namespace="jobs")),
    path('contact-us/',include("contact.urls",namespace='contact-us')),
    path('api-auth/', include('rest_framework.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
import email
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
# Create your models here.

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    city=models.ForeignKey('City',null=True,on_delete=models.CASCADE )
    phone=models.CharField(max_length=100)
    image=models.ImageField(upload_to='profile/')

    def __str__(self)  :
        return str (self.user)
    
    
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        
class City(models.Model) :
    name=models.CharField(max_length=100)
    def __str__(self) :
        return self.name
    
    

    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Profile



class signupform(UserCreationForm):
    class Meta:
        model=User
        fields=["username","email","password1","password2"]

        
class Profile_edit_one(forms.ModelForm):
    class Meta :
        model=User
        fields=["username","first_name","last_name","email"]
        
class Profile_edit_tow(forms.ModelForm):
    class Meta :
        model=Profile
        fields=["city","phone","image"]

accounts/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from .forms import signupform, Profile, Profile_edit_one, Profile_edit_tow
from django.contrib.auth import authenticate, login
from .models import Profile

# Create your views here.

# signup-------------------------


def signup(requset):
    if requset.method == "POST":
        form = signupform(requset.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(requset, user)
        return redirect("/accounts/profile")
    else:
        form = signupform()
    return render(requset, "registration/signup.html", {'form': form})

# profile-------------------------

def profile(requset):
    My_profile = Profile.objects.get(user=requset.user)
    return render(requset, "profile/profile.html", {'My_profile': My_profile})

# profile_edit-------------------------

def profile_edit(requset):
    profile = Profile.objects.get(user=requset.user)
    if requset.method == "POST":
        profile_edit_one = Profile_edit_one(
            requset.POST, instance=requset.user)
        profile_edit_tow = Profile_edit_tow(
            requset.POST, requset.FILES, instance=profile)
        if profile_edit_one.is_valid() and profile_edit_tow.is_valid():
            profile_edit_one.save()
            profile_edit_tow.save(commit=False)
            profile_edit_tow.user = requset.user
            profile_edit_tow.save
            return redirect(reverse("accounts:profile"))
    else:
        profile_edit_one = Profile_edit_one(instance=requset.user)
        profile_edit_tow = Profile_edit_tow(instance=profile)
    return render(requset, "profile/profile_edit.html", {'profile_edit_one': profile_edit_one, 'profile_edit_tow': profile_edit_tow})

accounts/templates/profile/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{job_detail}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 mx-auto">
                <div class="job_sumary">
                    <div class="summery_header">
                        <h3>Job Summery</h3>
                    </div>
                    
                    <div class="job_content">
                        <ul>
                            <li>Name: <span>{{My_profile}}</span></li>
                            <li>Email: <span>{{My_profile.user.email}}</span></li>
                            <li>phone: <span>{{My_profile.phone}}</span></li>
                            <li>city: <span>{{My_profile.city}}</span></li>
                            <img style="width:100px ;" src="{{My_profile.image.url}}" alt="">
                            <button class="boxed-btn3 w-100 my-3" type="submit"><a href="{% url 'accounts:profile_edit' %}" class="text-white ">edit profile</a></button>
                    </div>
                </div>
            
            </div>
        </div>
    </div>
</div>
{% endblock body %}

accounts/templates/profile/profile_edit.html
  {% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{job_detail}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <div class="job_sumary">
                    <div class="summery_header">
                        <h3>Job Summery</h3>
                    </div>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form  profile_edit_one %}
                        {% bootstrap_form  profile_edit_tow %}
                        {% buttons %}
                        <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                        {% endbuttons %}
                      </form>
                </div>
            
            </div>
        </div>
    </div>
</div>
{% endblock body %}