accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns = [
    path("signup",views.signup,name="signup"),
    path("profile",views.profile,name="profile"),
    path("profile/edit",views.profile_edit,name="profile_edit")
] 

contact/urls.py
from django.urls import path
from . import views

app_name="contact-us"
urlpatterns = [
    path("contact",views.contact,name="contact"),
    path("done",views.done,name="done")
]

job/urls.py
from django.urls import path
from . import views
from .import api

app_name="job"
urlpatterns = [
    path("job_list",views.job_list,name="job_list"),
    path("add_job",views.add_jobs,name="add_job"),
    path("<str:slug>",views.job_detail,name="job_detail"),
    
    #API
    path("api/list",api.API,name="api"),
    path("api/list/<str:id>",api.API_detail,name="api"),
       
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/',include("django.contrib.auth.urls")),
    path('accounts/',include("accounts.urls",namespace="accounts")),
    path('admin/', admin.site.urls),
    path('home/',include("home.urls")),
    path('blog/',include("blog.urls")),
    path('accounts/',include("accounts.urls")),
    path('jobs/',include("job.urls",namespace="jobs")),
    path('contact-us/',include("contact.urls",namespace='contact-us')),
    path('api-auth/', include('rest_framework.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{%load static %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Job Board</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- <link rel="manifest" href="site.webmanifest"> -->
  <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
  <!-- Place favicon.ico in the root directory -->

  <!-- CSS here -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
  <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
  <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
  <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">

  <link rel="stylesheet" href="{% static 'css/style.css'%}">
  <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
</head>

<body>
  <!--[if lte IE 9]>
               <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
           <![endif]-->

  <!-- header-start -->
  <header>
    <div class="header-area ">
      <div id="sticky-header" class="main-header-area">
        <div class="container-fluid ">
          <div class="header_bottom_border">
            <div class="row align-items-center">
              <div class="col-xl-3 col-lg-2">
                <div class="logo">
                  <a href="index.html">
                    <img src="img/logo.png" alt="">
                  </a>
                </div>
              </div>
              <div class="col-xl-6 col-lg-7">
                <div class="main-menu  d-none d-lg-block">
                  <nav>
                    <ul id="navigation">
                      <li><a href="{% url 'jobs:job_list' %}">home</a></li>
                      <li><a href="{% url 'jobs:job_list' %}">Browse Job</a></li>
                      <li><a href="{% url 'contact-us:contact' %}">Contact</a></li>
                    </ul>
                  </nav>
                </div>
              </div>
              <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                <div class="Appointment">
                  {% if user.is_authenticated %}
                  <div class="phone_num d-none d-xl-block">
                    <a href="{% url 'accounts:profile' %}">profile</a>
                  </div>

                  {% else %}

                  <div class="phone_num d-none d-xl-block">
                    <a href="{% url 'login' %}">Log in</a>
                  </div>
                  {% endif %}

                  <div class="d-none d-lg-block">
                    <a class="boxed-btn3" href="{% url 'jobs:add_job'  %}">add a Job</a>
                  </div>
                </div>
              </div>
              <div class="col-12">
                <div class="mobile_menu d-block d-lg-none"></div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </header>
  <!-- header-end -->

  {% block body %}
  {% endblock body %}


  <!-- footer start -->
  <footer class="footer">
    <div class="footer_top">
      <div class="container">
        <div class="row">
          <div class="col-xl-3 col-md-6 col-lg-3">
            <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
              <div class="footer_logo">
                <a href="#">
                  <img src="img/logo.png" alt="">
                </a>
              </div>
              <p>
                finloan@support.com <br>
                +10 873 672 6782 <br>
                600/D, Green road, NewYork
              </p>
              <div class="socail_links">
                <ul>
                  <li>
                    <a href="#">
                      <i class="ti-facebook"></i>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="fa fa-google-plus"></i>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="fa fa-twitter"></i>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="fa fa-instagram"></i>
                    </a>
                  </li>
                </ul>
              </div>

            </div>
          </div>
          <div class="col-xl-2 col-md-6 col-lg-2">
            <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
              <h3 class="footer_title">
                Company
              </h3>
              <ul>
                <li><a href="#">About </a></li>
                <li><a href="#"> Pricing</a></li>
                <li><a href="#">Carrier Tips</a></li>
                <li><a href="#">FAQ</a></li>
              </ul>

            </div>
          </div>
          <div class="col-xl-3 col-md-6 col-lg-3">
            <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
              <h3 class="footer_title">
                Category
              </h3>
              <ul>
                <li><a href="#">Design & Art</a></li>
                <li><a href="#">Engineering</a></li>
                <li><a href="#">Sales & Marketing</a></li>
                <li><a href="#">Finance</a></li>
              </ul>
            </div>
          </div>
          <div class="col-xl-4 col-md-6 col-lg-4">
            <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
              <h3 class="footer_title">
                Subscribe
              </h3>
              <form action="#" class="newsletter_form">
                <input type="text" placeholder="Enter your mail">
                <button type="submit">Subscribe</button>
              </form>
              <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
                luckily.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
      <div class="container">
        <div class="footer_border"></div>
        <div class="row">
          <div class="col-xl-12">
            <p class="copy_right text-center">
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              Copyright &copy;
              <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made
              with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com"
                target="_blank">Colorlib</a>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!--/ footer end  -->

  <!-- link that opens popup -->
  <!-- JS here -->
  <script src="{ %static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
  <script src="{ %static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
  <script src="{ %static 'js/popper.min.js' %}"></script>
  <script src="{ %static 'js/bootstrap.min.js' %}"></script>
  <script src="{ %static 'js/owl.carousel.min.js' %}"></script>
  <script src="{ %static 'js/isotope.pkgd.min.js' %}"></script>
  <script src="{ %static 'js/ajax-form.js' %}"></script>
  <script src="{ %static 'js/waypoints.min.js' %}"></script>
  <script src="{ %static 'js/jquery.counterup.min.js' %}"></script>
  <script src="{ %static 'js/imagesloaded.pkgd.min.js' %}"></script>
  <script src="{ %static 'js/scrollIt.js' %}"></script>
  <script src="{ %static 'js/jquery.scrollUp.min.js' %}"></script>
  <script src="{ %static 'js/wow.min.js' %}"></script>
  <script src="{ %static 'js/nice-select.min.js' %}"></script>
  <script src="{ %static 'js/jquery.slicknav.min.js' %}"></script>
  <script src="{ %static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{ %static 'js/plugins.js' %}"></script>
  <!-- <script src="{ %static 'js/gijgo.min.js' %}"></script> -->
  <script src="{ %static 'js/range.js' %}"></script>



  <!--contact js-->
  <script src="{ %static 'js/contact.js' %}"></script>
  <script src="{ %static 'js/jquery.ajaxchimp.min.js' %}"></script>
  <script src="{ %static 'js/jquery.form.js' %}"></script>
  <script src="{ %static 'js/jquery.validate.min.js' %}"></script>
  <script src="{ %static 'js/mail-script.js' %}"></script>


  <script src="{ %static 'js/main.js' %}"></script>


  <script>
    $(function () {
      $("#slider-range").slider({
        range: true,
        min: 0,
        max: 24600,
        values: [750, 24600],
        slide: function (event, ui) {
          $("#amount").val("$" + ui.values[0] + " - $" + ui.values[1] + "/ Year");
        }
      });
      $("#amount").val("$" + $("#slider-range").slider("values", 0) +
        " - $" + $("#slider-range").slider("values", 1) + "/ Year");
    });
  </script>
</body>

</html>

templates/base_generic.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
  <div class="container">

  </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 m-auto">
        <div class="apply_job_form white-bg ">
    {% block content %}      
    {% endblock content %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock body %}